# Apple Silicon (M1/M2/M3) Configuration
# Optimized for Apple's Metal Performance Shaders

data:
  data_dir: "./data/volumes"
  annotation_dir: "./data/annotations"
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  slice_axis: 2
  batch_size: 8
  img_size: [224, 224]
  target_spacing: [1.0, 1.0, 1.0]
  target_size: [224, 224, 64]
  use_adaptive_hu_normalization: true
  adaptive_hu_lower_percentile: 0.5
  adaptive_hu_upper_percentile: 99.5

compute:
  devices: 1                           # Single device for MPS
  accelerator: "mps"                   # Metal Performance Shaders
  strategy: "auto"                     # No multi-GPU for MPS
  precision: "32"                      # MPS works better with full precision
  num_workers: 4                       # Good balance for Apple Silicon

model:
  img_size: [224, 224]
  in_channels: 1
  out_channels: 1
  features: [32, 32, 64, 128, 256, 32]
  activation: "PRELU"
  spatial_dims: 2
  slice_axis: 2

training:
  epochs: 100
  batch_size: 8
  learning_rate: 1e-4
  optimizer: "AdamW"
  loss_function: "dicece"
  scheduler: "ReduceLROnPlateau"
  scheduler_kwargs:
    patience: 10
    factor: 0.5
    min_lr: 1e-7
  patience: 15
  min_delta: 1e-6

wandb:
  enabled: true
  project: "nifti-apple-silicon"
  tags: ["mps", "apple-silicon", "metal"]
  name: null

output_dir: "./outputs/apple_silicon"