# Quick Start Configuration
# Minimal setup for getting started quickly with reasonable defaults

data:
  data_dir: "./data/volumes"
  annotation_dir: "./data/annotations"
  annotation_type: "ART"               # Target annotation type: "ART", "RA", "S_FAT"
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  slice_axis: 2
  inference_chunk_size: 4
  img_size: [128, 128]                 # Small size for quick training
  target_spacing: [1.0, 1.0, 1.0]
  target_size: [128, 128, 32]
  use_adaptive_hu_normalization: true
  adaptive_hu_lower_percentile: 0.5
  adaptive_hu_upper_percentile: 99.5

compute:
  devices: "auto"                      # Use available GPU or CPU
  accelerator: "gpu"                   # Try GPU first, fallback to CPU
  strategy: "auto"                     # Let Lightning choose best strategy
  precision: "32"                      # Full precision for stability
  num_workers: 2                       # Fewer workers for quick start

model:
  img_size: [128, 128]
  in_channels: 1
  out_channels: 1
  features: [16, 32, 64, 128, 64, 16]  # Simple architecture
  activation: "RELU"
  spatial_dims: 2
  slice_axis: 2

training:
  epochs: 20                           # Quick training
  inference_chunk_size: 4
  learning_rate: 1e-3
  optimizer: "Adam"
  loss_function: "dice"
  patience: 5
  min_delta: 1e-4

wandb:
  enabled: false                       # Disable for quick testing
  project: "nifti-quick-start"

output_dir: "./outputs/quick_start"